apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-service
  name: assisted-service
  namespace: REPLACE_NAMESPACE
spec:
  ports:
    - name: assisted-service
      port: 8090
      protocol: TCP
      targetPort: 8090
    - name: assisted-service2
      port: 8092
      protocol: TCP
      targetPort: 8092
  selector:
    app: assisted-service
  type: LoadBalancer
status:
  loadBalancer: {}
