// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetStatusInfoHandlerFunc turns a function with the right signature into a set status info handler
type SetStatusInfoHandlerFunc func(SetStatusInfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SetStatusInfoHandlerFunc) Handle(params SetStatusInfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SetStatusInfoHandler interface for that can handle valid set status info params
type SetStatusInfoHandler interface {
	Handle(SetStatusInfoParams, interface{}) middleware.Responder
}

// NewSetStatusInfo creates a new http.Handler for the set status info operation
func NewSetStatusInfo(ctx *middleware.Context, handler SetStatusInfoHandler) *SetStatusInfo {
	return &SetStatusInfo{Context: ctx, Handler: handler}
}

/*SetStatusInfo swagger:route POST /clusters/{cluster_id}/status_info installer setStatusInfo

Set cluster status info

*/
type SetStatusInfo struct {
	Context *middleware.Context
	Handler SetStatusInfoHandler
}

func (o *SetStatusInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetStatusInfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
