// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewSetStatusInfoParams creates a new SetStatusInfoParams object
// with the default values initialized.
func NewSetStatusInfoParams() *SetStatusInfoParams {
	var ()
	return &SetStatusInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetStatusInfoParamsWithTimeout creates a new SetStatusInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetStatusInfoParamsWithTimeout(timeout time.Duration) *SetStatusInfoParams {
	var ()
	return &SetStatusInfoParams{

		timeout: timeout,
	}
}

// NewSetStatusInfoParamsWithContext creates a new SetStatusInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetStatusInfoParamsWithContext(ctx context.Context) *SetStatusInfoParams {
	var ()
	return &SetStatusInfoParams{

		Context: ctx,
	}
}

// NewSetStatusInfoParamsWithHTTPClient creates a new SetStatusInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetStatusInfoParamsWithHTTPClient(client *http.Client) *SetStatusInfoParams {
	var ()
	return &SetStatusInfoParams{
		HTTPClient: client,
	}
}

/*SetStatusInfoParams contains all the parameters to send to the API endpoint
for the set status info operation typically these are written to a http.Request
*/
type SetStatusInfoParams struct {

	/*ClusterID*/
	ClusterID strfmt.UUID
	/*StatusInfo*/
	StatusInfo models.ClusterStatusInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set status info params
func (o *SetStatusInfoParams) WithTimeout(timeout time.Duration) *SetStatusInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set status info params
func (o *SetStatusInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set status info params
func (o *SetStatusInfoParams) WithContext(ctx context.Context) *SetStatusInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set status info params
func (o *SetStatusInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set status info params
func (o *SetStatusInfoParams) WithHTTPClient(client *http.Client) *SetStatusInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set status info params
func (o *SetStatusInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the set status info params
func (o *SetStatusInfoParams) WithClusterID(clusterID strfmt.UUID) *SetStatusInfoParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the set status info params
func (o *SetStatusInfoParams) SetClusterID(clusterID strfmt.UUID) {
	o.ClusterID = clusterID
}

// WithStatusInfo adds the statusInfo to the set status info params
func (o *SetStatusInfoParams) WithStatusInfo(statusInfo models.ClusterStatusInfo) *SetStatusInfoParams {
	o.SetStatusInfo(statusInfo)
	return o
}

// SetStatusInfo adds the statusInfo to the set status info params
func (o *SetStatusInfoParams) SetStatusInfo(statusInfo models.ClusterStatusInfo) {
	o.StatusInfo = statusInfo
}

// WriteToRequest writes these params to a swagger request
func (o *SetStatusInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID.String()); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.StatusInfo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
