// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// SetStatusInfoReader is a Reader for the SetStatusInfo structure.
type SetStatusInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetStatusInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSetStatusInfoNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetStatusInfoBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSetStatusInfoUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetStatusInfoForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetStatusInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewSetStatusInfoMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetStatusInfoInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewSetStatusInfoServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetStatusInfoNoContent creates a SetStatusInfoNoContent with default headers values
func NewSetStatusInfoNoContent() *SetStatusInfoNoContent {
	return &SetStatusInfoNoContent{}
}

/*SetStatusInfoNoContent handles this case with default header values.

Success.
*/
type SetStatusInfoNoContent struct {
}

func (o *SetStatusInfoNoContent) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoNoContent ", 204)
}

func (o *SetStatusInfoNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetStatusInfoBadRequest creates a SetStatusInfoBadRequest with default headers values
func NewSetStatusInfoBadRequest() *SetStatusInfoBadRequest {
	return &SetStatusInfoBadRequest{}
}

/*SetStatusInfoBadRequest handles this case with default header values.

Error.
*/
type SetStatusInfoBadRequest struct {
	Payload *models.Error
}

func (o *SetStatusInfoBadRequest) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoBadRequest  %+v", 400, o.Payload)
}

func (o *SetStatusInfoBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusInfoBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoUnauthorized creates a SetStatusInfoUnauthorized with default headers values
func NewSetStatusInfoUnauthorized() *SetStatusInfoUnauthorized {
	return &SetStatusInfoUnauthorized{}
}

/*SetStatusInfoUnauthorized handles this case with default header values.

Unauthorized.
*/
type SetStatusInfoUnauthorized struct {
	Payload *models.InfraError
}

func (o *SetStatusInfoUnauthorized) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoUnauthorized  %+v", 401, o.Payload)
}

func (o *SetStatusInfoUnauthorized) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *SetStatusInfoUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoForbidden creates a SetStatusInfoForbidden with default headers values
func NewSetStatusInfoForbidden() *SetStatusInfoForbidden {
	return &SetStatusInfoForbidden{}
}

/*SetStatusInfoForbidden handles this case with default header values.

Forbidden.
*/
type SetStatusInfoForbidden struct {
	Payload *models.InfraError
}

func (o *SetStatusInfoForbidden) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoForbidden  %+v", 403, o.Payload)
}

func (o *SetStatusInfoForbidden) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *SetStatusInfoForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoNotFound creates a SetStatusInfoNotFound with default headers values
func NewSetStatusInfoNotFound() *SetStatusInfoNotFound {
	return &SetStatusInfoNotFound{}
}

/*SetStatusInfoNotFound handles this case with default header values.

Error.
*/
type SetStatusInfoNotFound struct {
	Payload *models.Error
}

func (o *SetStatusInfoNotFound) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoNotFound  %+v", 404, o.Payload)
}

func (o *SetStatusInfoNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoMethodNotAllowed creates a SetStatusInfoMethodNotAllowed with default headers values
func NewSetStatusInfoMethodNotAllowed() *SetStatusInfoMethodNotAllowed {
	return &SetStatusInfoMethodNotAllowed{}
}

/*SetStatusInfoMethodNotAllowed handles this case with default header values.

Method Not Allowed.
*/
type SetStatusInfoMethodNotAllowed struct {
	Payload *models.Error
}

func (o *SetStatusInfoMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *SetStatusInfoMethodNotAllowed) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusInfoMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoInternalServerError creates a SetStatusInfoInternalServerError with default headers values
func NewSetStatusInfoInternalServerError() *SetStatusInfoInternalServerError {
	return &SetStatusInfoInternalServerError{}
}

/*SetStatusInfoInternalServerError handles this case with default header values.

Error.
*/
type SetStatusInfoInternalServerError struct {
	Payload *models.Error
}

func (o *SetStatusInfoInternalServerError) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoInternalServerError  %+v", 500, o.Payload)
}

func (o *SetStatusInfoInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusInfoInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInfoServiceUnavailable creates a SetStatusInfoServiceUnavailable with default headers values
func NewSetStatusInfoServiceUnavailable() *SetStatusInfoServiceUnavailable {
	return &SetStatusInfoServiceUnavailable{}
}

/*SetStatusInfoServiceUnavailable handles this case with default header values.

Unavailable.
*/
type SetStatusInfoServiceUnavailable struct {
	Payload *models.Error
}

func (o *SetStatusInfoServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /clusters/{cluster_id}/status_info][%d] setStatusInfoServiceUnavailable  %+v", 503, o.Payload)
}

func (o *SetStatusInfoServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusInfoServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
