// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AwsPlatform aws platform specific configuration upon which to perform the installation
//
// swagger:model aws-platform
type AwsPlatform struct {

	// access_key
	AccessKey *string `json:"access_key,omitempty"`

	// number of worker nodes
	ComputeReplicas *int64 `json:"computeReplicas,omitempty"`

	// region
	Region *string `json:"region,omitempty"`

	// secret
	// Format: password
	Secret *strfmt.Password `json:"secret,omitempty"`
}

// Validate validates this aws platform
func (m *AwsPlatform) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecret(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsPlatform) validateSecret(formats strfmt.Registry) error {

	if swag.IsZero(m.Secret) { // not required
		return nil
	}

	if err := validate.FormatOf("secret", "body", "password", m.Secret.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AwsPlatform) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsPlatform) UnmarshalBinary(b []byte) error {
	var res AwsPlatform
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
