// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ClusterHighAvailabilityMode Guaranteed availability of the installed cluster. 'Full' installs a Highly-Available cluster
// over multiple master nodes whereas 'None' installs a full cluster over one node.
//
//
// swagger:model cluster_high_availability_mode
type ClusterHighAvailabilityMode string

func NewClusterHighAvailabilityMode(value ClusterHighAvailabilityMode) *ClusterHighAvailabilityMode {
	v := value
	return &v
}

const (

	// ClusterHighAvailabilityModeFull captures enum value "Full"
	ClusterHighAvailabilityModeFull ClusterHighAvailabilityMode = "Full"

	// ClusterHighAvailabilityModeNone captures enum value "None"
	ClusterHighAvailabilityModeNone ClusterHighAvailabilityMode = "None"
)

// for schema
var clusterHighAvailabilityModeEnum []interface{}

func init() {
	var res []ClusterHighAvailabilityMode
	if err := json.Unmarshal([]byte(`["Full","None"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clusterHighAvailabilityModeEnum = append(clusterHighAvailabilityModeEnum, v)
	}
}

func (m ClusterHighAvailabilityMode) validateClusterHighAvailabilityModeEnum(path, location string, value ClusterHighAvailabilityMode) error {
	if err := validate.EnumCase(path, location, value, clusterHighAvailabilityModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this cluster high availability mode
func (m ClusterHighAvailabilityMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateClusterHighAvailabilityModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this cluster high availability mode based on context it is used
func (m ClusterHighAvailabilityMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
