// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// HighAvailabilityMode Guaranteed availability of the installed cluster. 'Full' installs a Highly-Available cluster
// over multiple master nodes whereas 'None' installs a full cluster over one node.
//
//
// swagger:model high_availability_mode
type HighAvailabilityMode string

func NewHighAvailabilityMode(value HighAvailabilityMode) *HighAvailabilityMode {
	v := value
	return &v
}

const (

	// HighAvailabilityModeFull captures enum value "Full"
	HighAvailabilityModeFull HighAvailabilityMode = "Full"

	// HighAvailabilityModeNone captures enum value "None"
	HighAvailabilityModeNone HighAvailabilityMode = "None"
)

// for schema
var highAvailabilityModeEnum []interface{}

func init() {
	var res []HighAvailabilityMode
	if err := json.Unmarshal([]byte(`["Full","None"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		highAvailabilityModeEnum = append(highAvailabilityModeEnum, v)
	}
}

func (m HighAvailabilityMode) validateHighAvailabilityModeEnum(path, location string, value HighAvailabilityMode) error {
	if err := validate.EnumCase(path, location, value, highAvailabilityModeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this high availability mode
func (m HighAvailabilityMode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHighAvailabilityModeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this high availability mode based on context it is used
func (m HighAvailabilityMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
