// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InstallCmdRequest install cmd request
//
// swagger:model install_cmd_request
type InstallCmdRequest struct {

	// Service base url to send logs to
	// Required: true
	BaseURL *string `json:"base_url"`

	// Boot device to write image on
	// Required: true
	Bootdevice *string `json:"bootdevice"`

	// Path to certificate on the nodes
	CaCertPath string `json:"ca_cert_path,omitempty"`

	// Check CVO status if needed
	CheckCvo *bool `json:"check_cvo,omitempty"`

	// Cluster id
	// Required: true
	// Format: uuid
	ClusterID *strfmt.UUID `json:"cluster_id"`

	// Assisted installer controller image
	// Required: true
	ControllerImage *string `json:"controller_image"`

	// List of disks to format
	DiskToFormat []string `json:"disk_to_format"`

	// high availability mode
	// Required: true
	HighAvailabilityMode *HighAvailabilityMode `json:"high_availability_mode"`

	// Host id
	// Required: true
	// Format: uuid
	HostID *strfmt.UUID `json:"host_id"`

	// Infra env id
	// Required: true
	// Format: uuid
	InfraEnvID *strfmt.UUID `json:"infra_env_id"`

	// Skip ceritifacate verification
	// Required: true
	Insecure *bool `json:"insecure"`

	// Machine config operator image
	McoImage string `json:"mco_image,omitempty"`

	// Must-gather images to use
	MustGatherImage string `json:"must_gather_image,omitempty"`

	// Version of the OpenShift cluster.
	OpenshiftVersion string `json:"openshift_version,omitempty"`

	// proxy
	Proxy *Proxy `json:"proxy,omitempty" gorm:"embedded;embeddedPrefix:proxy_"`

	// role
	// Required: true
	Role *HostRole `json:"role"`
}

// Validate validates this install cmd request
func (m *InstallCmdRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBootdevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateControllerImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHighAvailabilityMode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInfraEnvID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInsecure(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallCmdRequest) validateBaseURL(formats strfmt.Registry) error {

	if err := validate.Required("base_url", "body", m.BaseURL); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateBootdevice(formats strfmt.Registry) error {

	if err := validate.Required("bootdevice", "body", m.Bootdevice); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("cluster_id", "body", m.ClusterID); err != nil {
		return err
	}

	if err := validate.FormatOf("cluster_id", "body", "uuid", m.ClusterID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateControllerImage(formats strfmt.Registry) error {

	if err := validate.Required("controller_image", "body", m.ControllerImage); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateHighAvailabilityMode(formats strfmt.Registry) error {

	if err := validate.Required("high_availability_mode", "body", m.HighAvailabilityMode); err != nil {
		return err
	}

	if err := validate.Required("high_availability_mode", "body", m.HighAvailabilityMode); err != nil {
		return err
	}

	if m.HighAvailabilityMode != nil {
		if err := m.HighAvailabilityMode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("high_availability_mode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("high_availability_mode")
			}
			return err
		}
	}

	return nil
}

func (m *InstallCmdRequest) validateHostID(formats strfmt.Registry) error {

	if err := validate.Required("host_id", "body", m.HostID); err != nil {
		return err
	}

	if err := validate.FormatOf("host_id", "body", "uuid", m.HostID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateInfraEnvID(formats strfmt.Registry) error {

	if err := validate.Required("infra_env_id", "body", m.InfraEnvID); err != nil {
		return err
	}

	if err := validate.FormatOf("infra_env_id", "body", "uuid", m.InfraEnvID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateInsecure(formats strfmt.Registry) error {

	if err := validate.Required("insecure", "body", m.Insecure); err != nil {
		return err
	}

	return nil
}

func (m *InstallCmdRequest) validateProxy(formats strfmt.Registry) error {
	if swag.IsZero(m.Proxy) { // not required
		return nil
	}

	if m.Proxy != nil {
		if err := m.Proxy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("proxy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("proxy")
			}
			return err
		}
	}

	return nil
}

func (m *InstallCmdRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	if m.Role != nil {
		if err := m.Role.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this install cmd request based on the context it is used
func (m *InstallCmdRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHighAvailabilityMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProxy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InstallCmdRequest) contextValidateHighAvailabilityMode(ctx context.Context, formats strfmt.Registry) error {

	if m.HighAvailabilityMode != nil {
		if err := m.HighAvailabilityMode.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("high_availability_mode")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("high_availability_mode")
			}
			return err
		}
	}

	return nil
}

func (m *InstallCmdRequest) contextValidateProxy(ctx context.Context, formats strfmt.Registry) error {

	if m.Proxy != nil {
		if err := m.Proxy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("proxy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("proxy")
			}
			return err
		}
	}

	return nil
}

func (m *InstallCmdRequest) contextValidateRole(ctx context.Context, formats strfmt.Registry) error {

	if m.Role != nil {
		if err := m.Role.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("role")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InstallCmdRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstallCmdRequest) UnmarshalBinary(b []byte) error {
	var res InstallCmdRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
